### ISSUE TITLE
No sdist available on PyPI

### ISSUE THREAD

**Issue by houseofsuns** [cde-ev/subman#1]
Currently there is only a wheel available on PyPI. Please also provide a source bundle.

For reference: schulze-condorcet does have an sdist.

**Comment by houseofsuns** [comment]
*ping*

**Comment by houseofsuns** [comment]
schulze-condorcet got another release with sdist.

**Comment by larsesser** [comment]
This is strange, since the current publishing workflow should provide an sdist and wheel build... Please check this again after we published the next version of subman. If the error persists, I can take another look at this...

**Comment by houseofsuns** [comment]
We now have an sdist. *yeah*
